// flow-typed signature: 882273fa68a3e35f7f7a417d99e7ab2a
// flow-typed version: <<STUB>>/react-primitives-svg_v0.0.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-primitives-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-primitives-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-primitives-svg/example' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/lib/core.android' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/lib/core.ios' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/lib/core.sketch' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/lib/core.web' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/lib/index' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/src/core.android' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/src/core.ios' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/src/core.sketch' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/src/core.web' {
  declare module.exports: any;
}

declare module 'react-primitives-svg/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-primitives-svg/example.js' {
  declare module.exports: $Exports<'react-primitives-svg/example'>;
}
declare module 'react-primitives-svg/lib/core.android.js' {
  declare module.exports: $Exports<'react-primitives-svg/lib/core.android'>;
}
declare module 'react-primitives-svg/lib/core.ios.js' {
  declare module.exports: $Exports<'react-primitives-svg/lib/core.ios'>;
}
declare module 'react-primitives-svg/lib/core.sketch.js' {
  declare module.exports: $Exports<'react-primitives-svg/lib/core.sketch'>;
}
declare module 'react-primitives-svg/lib/core.web.js' {
  declare module.exports: $Exports<'react-primitives-svg/lib/core.web'>;
}
declare module 'react-primitives-svg/lib/index.js' {
  declare module.exports: $Exports<'react-primitives-svg/lib/index'>;
}
declare module 'react-primitives-svg/src/core.android.js' {
  declare module.exports: $Exports<'react-primitives-svg/src/core.android'>;
}
declare module 'react-primitives-svg/src/core.ios.js' {
  declare module.exports: $Exports<'react-primitives-svg/src/core.ios'>;
}
declare module 'react-primitives-svg/src/core.sketch.js' {
  declare module.exports: $Exports<'react-primitives-svg/src/core.sketch'>;
}
declare module 'react-primitives-svg/src/core.web.js' {
  declare module.exports: $Exports<'react-primitives-svg/src/core.web'>;
}
declare module 'react-primitives-svg/src/index.js' {
  declare module.exports: $Exports<'react-primitives-svg/src/index'>;
}
